### ISSUE TITLE
Name in local language vs name_en

### ISSUE THREAD

**Issue by klokan** [OSMNames/OSMNames#131]
We have deployed the latest data to https://osmnames.org/. There are many improvements in the data indeed. Thanks!

The change of precedence - shortly mentioned and made by @simran001 at https://github.com/OSMNames/OSMNames/issues/55#issuecomment-300159072
(on a ticket which is not closed!!!) introduces a usability disaster for most English speaking / latin reading world using the OSMNames search system.

Try to search for Japan, Egypt or Russia...
There is a reason why we had "name_en" as the default.

Yes, this can be done properly in future @sfkeller, but for now, the related ticket #55 remains opened, decisions there were not done and changing the precedence to native is definitely not a good idea.

The default language must be reverted now - and we have to redo the deployment and release of OSMNames data again, unfortunately.

@philippks are you still available to redo the release?
How long can it take to generate the world again?
Or do we (@KlokanTech and @MartinMikita) need to do that on our side?

**Comment by klokan** [comment]
I suggest releasing v2.0.1 as a bug fix release

**Comment by klokan** [comment]
The change which should be done for reverting is described at:
https://github.com/OSMNames/OSMNames/issues/55#issuecomment-303393661

**Comment by philippks** [comment]
hi @klokan 

Nice that you were able to deploy the newest data set, thanks!

You're right the current usability with the names is a chaos. Only small changes are necessary to change it back as before. I can do it the next days and could provide you a new export by mid of the week. This would also include #130.

@sfkeller do you agree with this?

**Comment by sfkeller** [comment]
Yes.

**Comment by klokan** [comment]
@philippks thank you a lot!

We wait until you make new release v2.0.1 and we are going to update the production search system then. Please don't delay this too much - the search is practically broken now and people will report this as a bug...

**Comment by philippks** [comment]
@klokan I just released the new version of the export:
https://github.com/OSMNames/OSMNames/releases/tag/v2.0.1

I'm looking forward to see the newest release in action (hope it is more useful now).

**Comment by MartinMikita** [comment]
Thanks @philippks 
Now it looks much better.
But there are some data with the local name instead of English, for an example:

![image](https://user-images.githubusercontent.com/2283182/30330457-6fdd5c46-97d5-11e7-82d8-b13ee6304fa4.png)

An actual JSON result for `Jaafar`:
```
{
      "wikipedia": "\"\"",
      "rank": 12087052.0,
      "county": "جعفر",
      "street": "\"\"",
      "wikidata": "\"\"",
      "country_code": "tn",
      "osm_id": "7114556",
      "housenumbers": "\"\"",
      "id": 61850,
      "city": "\"\"",
      "display_name": "جعفر, رواد, أريانة, تونس",
      "lon": 10.182697,
      "state": "أريانة",
      "boundingbox": [
        10.178007,
        36.890568,
        10.191524,
        36.940712
      ],
      "type": "administrative",
      "importance": 0.45,
      "lat": 36.915684,
      "class": "boundary",
      "name": "جعفر",
      "country": "Tunisia",
      "name_suffix": "\"\", TN",
      "osm_type": "relation",
      "place_rank": 12.0,
      "alternative_names": "Jaafar"
    },
```

OSMNames v2.0.1 JSON result:
```
{
      "wikipedia": "",
      "rank": 12251575.0,
      "county": "جعفر",
      "street": "",
      "wikidata": "",
      "country_code": "tn",
      "osm_id": "7114556",
      "housenumbers": "",
      "id": 67424,
      "city": "",
      "display_name": "جعفر, رواد, Ariana, Tunisia",
      "lon": 10.182697,
      "state": "Ariana",
      "boundingbox": [
        10.178007,
        36.890568,
        10.191524,
        36.940712
      ],
      "type": "administrative",
      "importance": 0.45,
      "lat": 36.915684,
      "class": "boundary",
      "name": "جعفر",
      "country": "Tunisia",
      "name_suffix": "",
      "osm_type": "relation",
      "place_rank": 12.0,
      "alternative_names": "Jaafar"
    }
```

**Comment by klokan** [comment]
So country, name and display_name still not in English - and instead alternative_names contains English..?

Re-release of 2.0.1 again with a proper fix? @philippks

**Comment by MartinMikita** [comment]
They are for the most of the data, like Egypt, Russia, Japan.
But looking for the Japan (when I typed `jaa` by mistake) I found this example.

![image](https://user-images.githubusercontent.com/2283182/30332523-b8fe605a-97da-11e7-9851-5ef54e8e0e54.png)

**Comment by simran001** [comment]
Hi @MartinMikita 
Just adding my two cents, in the particular case of Jaafar the issue might be because of the OpenStreetMap data itself. Here is the [search result for OSM ID 7114556](https://www.openstreetmap.org/relation/7114556#map=13/36.9157/10.1848). It does not have a tag for the English name (_name:en_). The value for _name:fr_ is Jaafar, and since in OSMNames we prefer the local name over the French name (name_en > name > name_fr etc), the value of the _name_ tag (which is Arabic) is picked up.

**Comment by simran001** [comment]
In OSMNames we get the English name from the name:en tag. But there might be several places which do not have this name:en tag. This becomes a problem in countries that do not use the latin character set (e.g. Russia, Japan, Arabic speaking countries). Prof Stefan had suggested that we can transliterate such names to latin characters, but we haven't been able to implement transliteration in OSMNames yet.

**Comment by philippks** [comment]
@klokan as @simran001 pointed out, does the [specific example](https://www.openstreetmap.org/relation/7114556#map=13/36.9157/10.1848) do not have a `name:en` tag. The alternative_name which looks english is actually the value of the `name:fr` tag.

Most likely this issue already existed in the release 1.1 and should therefore be solved in a different issue (which won't be that simple...).

**Comment by MartinMikita** [comment]
Okay, thanks for the explanation, we will create a new ticket and this can be closed, as this is not the source of this issue.

OSMNames v2.0.1 data was released yesterday in OSMNames.org.
Thanks again for a great job!
